module C = Configurator.V1

let config = Hashtbl.create 10

let prefix = Sys.getenv_opt "HOME" |> Option.value ~default:"/usr"

let flag arg ~default ~doc =
  let env_var = String.uppercase_ascii arg in
  let set value = Hashtbl.replace config env_var value in
  set default ;
  ("--" ^ arg, Arg.String set, doc)

let args = [
  flag "prefix" ~default:prefix
    ~doc:"DIR Destination where the artifacts will be installed"
] |> Arg.align

let () =
  C.main ~args ~name:"configure" @@ fun _ ->
  config
  |> Hashtbl.to_seq
  |> Seq.map (fun (k, v) -> Printf.sprintf "export %s=%s" k v)
  |> Seq.cons "# This file was autogenerated by the configure script"
  |> Seq.iter print_endline
